import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../components/header'
import Footer from '../components/footer'
import Script from 'next/script'
import 'animate.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'narrative',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Script src="/Scripts/toggle.js" strategy="beforeInteractive" />
        <Header/>
        {children}
        <Footer/>
      
        </body>
        
    </html>
  )
}
